baseURL: 'https://yokomasa.netlify.app/'
languageCode: 'ja-jp'
title: 'Masato Yokota'
theme: 'myTheme'
defaultContentLanguage: jp
languages:
  jp:
    title: 'Masato Yokota'
    weight: 1
    menu:
      mymenu:
      - name: 'Works'
        url: '/works'
  en:
    title: 'Masato Yokota'
    weight: 2
    menu:
      mymenu:
      - name: 'Works'
        url: '/works'